POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "641c590b0ec438c053e97273",
    "username" : "Tochi Edit",
    "email" : "derek@derek.com",
    "password" : "dwwrwrabcdefghik1",
    "favRoute" : "Red"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "641c590b0ec438c053e97273"
}

###
POST  http://localhost:8081/user/deleteAll

### get all developers
GET http://localhost:8081/developer/getAll



### edit developer
POST http://localhost:8081/user/editDeveloper
Content-Type: application/json

{
    "developerId": "643ea592f37d8f545ea258b1",
    "fName": "Archie",
    "lName": "Berduo",
    "projDescription": "Front-End Developer I have gained alot of experience in Front-End Development through OpenLayers Map layering, Webpage UX design  and some Back-End experience through the use of editi text from test to the database. My main opportunity that I wish to develop in the future is to fully understand the Front-end capability to change Back-End files from user input and more UI styling."
}