POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "641c590b0ec438c053e97273",
    "username" : "Tochi Edit",
    "email" : "derek@derek.com",
    "password" : "dwwrwrabcdefghik1",
    "favRoute" : "Red"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll

### get all developers
GET http://localhost:8081/developer/getAll

### get developer by id
GET http://localhost:8081/developer/getDeveloperById
Content-Type: application/json 

{
    "developerId" : "642c351d33f7fa1ca979051b"
}

### create developer currently unavaliable
POST http://localhost:8081/developer/createDeveloper

{
    fName : "Archie",
    lName : "Berduo",
    projDescrition : "This is a project description",
}

### edit developer Currently Unavaliable
POST http://localhost:8081/developer/editDeveloper
Content-Type: application/json 

{
    "developerId" : "642c351d33f7fa1ca979051b",
    "fName" : "Archie",
    "lName" : "Berduo",
    "projDescrition" : "This is a project description",
}

### delete developer Currently Unavaliable
POST http://localhost:8081/developer/deleteDeveloper
Content-Type: application/json 

{
    "developerId" : "642c351d33f7fa1ca979051b"
}