POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "641c590b0ec438c053e97273",
    "username" : "Tochi Edit",
    "email" : "derek@derek.com",
    "password" : "dwwrwrabcdefghik1",
    "favRoute" : "Red"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "641c590b0ec438c053e97273"
}

###
POST  http://localhost:8081/user/deleteAll

### get all developers
GET http://localhost:8081/developer/getAll

### edit developer
POST http://localhost:8081/developer/editDeveloper
Content-Type: application/json 

{
    "developerId" : "642c351d33f7fa1ca979051b",
    "fName" : "Derek",
    "lName" : "Martineau",
    "projDescrition" : "This is a project description",
}